name: Deploy project

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # 先删除
        ARGS: '-avzr --delete'
        SOURCE: "."
        # IP
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: "root"
        TARGET: "/home/3d/server"
        SCRIPT_AFTER: |
          cd /home/3d/server
          npm install
          cd /home/3d/
          docker compose down
          docker compose up -d
